import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { TiPlus } from "react-icons/ti";

import { AppointmentTable } from "~/components/admin/AppointmentTable";
import { usePagination } from "~/components/admin/usePagination";
import { UpdateLiveAppointmentStatus } from "~/components/LiveAppointment";
import { Loader } from "~/components/loader/Loader";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "~/components/ui/select";
import { api } from "~/utils/api";
import { useUser } from "~/utils/auth";
import { toTitleCase } from "~/utils/helper";

const Admin = () => {
  const [user] = useUser();
  const [slug, setSlug] = useState<string | null>(null);

  // * when admin views the page
  const doctorList = api.appointment.getAdminDoctorList.useQuery(undefined, {
    enabled: !!user && user.role === "ADMIN",
    onSuccess: (resp) => {
      if (resp.list.length > 0 && resp.list[0]?.slug) {
        setSlug(resp.list[0].slug);
      }
    },
  });

  // * when doctor views the page
  api.doctor.getSlug.useQuery(undefined, {
    enabled: !!user && user.role === "DOCTOR",
    onSuccess: (slug) => {
      setSlug(slug);
    },
  });

  const doctorInfo = api.doctor.getBySlug.useQuery(
    { slug: slug ?? "" },
    {
      enabled: !!slug,
    },
  );

  const { limit, onPaginationChange, skip, pagination } = usePagination();

  const appointments = api.appointment.getAppointments.useQuery(
    { slug: slug ?? "", limit, skip },
    {
      enabled: !!slug,
    },
  );

  const isViewerAdmin =
    user?.role === "ADMIN" &&
    doctorList.data &&
    doctorList.data.list.length > 0;

  if (doctorInfo.isLoading) {
    return <Loader />;
  }

  if (appointments.isError || doctorInfo.isError) {
    return <div>Error: {appointments?.error?.message}</div>;
  }

  const pageCount = Math.ceil(50 / limit);

  return (
    <>
      <Head>
        <title>
          Admin {toTitleCase(`${doctorInfo?.data?.user.name ?? "N/A"}`)}
        </title>
        <meta name="description" content="Generated by create-t3-app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-[20px] lg:mx-[90px] ">
        {isViewerAdmin && (
          <div className="mt-5">
            <Select
              defaultValue={doctorList.data.list[0]?.slug ?? ""}
              onValueChange={(value: string) => setSlug(value)}
            >
              <SelectTrigger className="lg:mx-auto lg:w-1/2">
                <SelectValue placeholder="Select Doctor" />
              </SelectTrigger>

              <SelectContent>
                {doctorList.data.list.map((doctor) => (
                  <SelectItem key={doctor.id} value={doctor.slug}>
                    {doctor.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        )}
        <h2 className="mt-5 text-[20px] font-semibold leading-[36px] tracking-[0.3px] lg:mt-10 lg:text-[30px]">
          Live Serial Update
        </h2>

        <div className="mt-4 flex items-center justify-between lg:mt-6">
          <div className="w-full md:w-1/2 lg:w-1/2">
            <Link
              href={`/admin/booking/${slug}`}
              className="flex w-fit items-center gap-2 rounded-[15px] bg-[#0099FF] px-[16px] py-[6px] text-[15px] font-bold leading-[30px] text-[#FFF]"
            >
              <TiPlus /> New Appointment
            </Link>
            <div>
              {slug && <UpdateLiveAppointmentStatus doctorSlug={slug} />}
            </div>
          </div>

          <div className="hidden overflow-hidden rounded-[15px] md:block md:w-5/12 lg:block lg:w-5/12">
            <Image
              src="/assets/images/appointment-serial.jpg"
              width={500}
              height={500}
              alt="appointment-serial"
              className="w-full"
            />
          </div>
        </div>

        <section className="mt-5 lg:mt-0">
          <h2 className="text-[20px] font-semibold leading-[36px] tracking-[0.3px] lg:text-[30px]">
            Patient Appointment List
          </h2>
          <AppointmentTable
            appointments={appointments?.data?.appointments ?? []}
            onPaginationChange={onPaginationChange}
            pagination={pagination}
            isLoading={appointments.isLoading}
            pageCount={pageCount}
          />
        </section>
      </main>
    </>
  );
};

export default Admin;
