export const diagnosisList = [
    { "name": "CBC" },
    { "name": "Endoscopy" },
    { "name": "MRI" },
    { "name": "X-ray" },
    { "name": "Ultrasound" },
    { "name": "CT Scan" },
    { "name": "EKG/ECG" },
    { "name": "Colonoscopy" },
    { "name": "Biopsy" },
    { "name": "Electrocardiogram" },
    { "name": "Blood Pressure Measurement" },
    { "name": "Blood Sugar Test" },
    { "name": "Thyroid Function Test" },
    { "name": "Liver Function Test" },
    { "name": "Kidney Function Test" },
    { "name": "Stress Test" },
    { "name": "Spirometry" },
    { "name": "Pap Smear" },
    { "name": "Mammography" },
    { "name": "Bone Density Test" },
    { "name": "Allergy Testing" },
    { "name": "Stool Culture" },
    { "name": "Urinalysis" },
    { "name": "TSH Test" },
    { "name": "C-Reactive Protein Test" },
    { "name": "Lipid Profile" },
    { "name": "Electroencephalogram (EEG)" },
    { "name": "Echocardiogram" },
    { "name": "Barium Swallow" },
    { "name": "Arthroscopy" },
    { "name": "Lumbar Puncture" },
    { "name": "Treadmill Stress Test" },
    { "name": "Skin Biopsy" },
    { "name": "Nerve Conduction Study" },
    { "name": "DEXA Scan" },
    { "name": "Throat Culture" },
    { "name": "Hemoglobin A1c Test" },
    { "name": "Prostate-Specific Antigen (PSA) Test" },
    { "name": "Glucose Tolerance Test" },
    { "name": "Fecal Occult Blood Test" },
    { "name": "Serum Creatinine Test" },
    { "name": "Electromyography (EMG)" },
    { "name": "Vitamin D Test" },
    { "name": "CT Angiography" },
    { "name": "Holter Monitor" },
    { "name": "Sigmoidoscopy" },
    { "name": "Hematocrit Test" },
    { "name": "Antinuclear Antibody Test (ANA)" },
    { "name": "Glaucoma Test" },
    { "name": "Thyroid Ultrasound" },
    { "name": "Hemoglobin Test" },
    { "name": "Electronystagmography" },
    { "name": "Cardiac Catheterization" },
    { "name": "Arterial Blood Gas Test" },
    { "name": "Cervical Screening" },
    { "name": "Genetic Testing" },
    { "name": "Hepatitis Panel" },
    { "name": "Calcium Blood Test" },
    { "name": "Liver Biopsy" },
    { "name": "Throat Swab Culture" },
    { "name": "Sputum Culture" },
    { "name": "Oxygen Saturation Test" },
    { "name": "Serum Electrolyte Test" },
    { "name": "Vitamin B12 Test" },
    { "name": "Follicle-Stimulating Hormone (FSH) Test" },
    { "name": "Luteinizing Hormone (LH) Test" },
    { "name": "Chest X-ray" },
    { "name": "Magnetic Resonance Angiography (MRA)" },
    { "name": "Hemoglobin Electrophoresis" },
    { "name": "Prothrombin Time (PT) Test" },
    { "name": "Activated Partial Thromboplastin Time (APTT) Test" },
    { "name": "Hormone Level Testing" },
    { "name": "Thyroid Antibody Test" },
    { "name": "Cultures (Blood, Urine, etc.)" },
    { "name": "Breath Test" },
    { "name": "Skin Patch Test" },
    { "name": "Computed Tomography Angiography (CTA)" },
    { "name": "Ankle-Brachial Index (ABI)" },
    { "name": "Semen Analysis" },
    { "name": "Lumbar MRI" },
    { "name": "Coronary Angiogram" },
    { "name": "Fetal Ultrasound" },
    { "name": "Holter Monitoring" },
    { "name": "Nuclear Stress Test" },
    { "name": "Surgical Biopsy" },
    { "name": "Sleep Study" },
    { "name": "Hysteroscopy" },
    { "name": "Colonography" },
    { "name": "Cystoscopy" },
    { "name": "Hepatic Function Panel" },
    { "name": "Cystography" },
    { "name": "Dual-Energy X-ray Absorptiometry (DEXA)" },
    { "name": "Laryngoscopy" },
    { "name": "KUB (Kidney, Ureter, Bladder) X-ray" },
    { "name": "Voiding Cystourethrogram (VCUG)" },
    { "name": "Esophagram" },
    { "name": "Intravenous Pyelogram (IVP)" },
    { "name": "Renal Ultrasound" },
    { "name": "Hemorrhoidectomy" },
    { "name": "Cholangiography" }
]
