import Head from "next/head";

import { DoctorTable } from "~/components/admin/DoctorTable";
import { Loader } from "~/components/loader/Loader";
import { api } from "~/utils/api";

const AdminDoctor = () => {
  const doctor = api.doctor.getAllDoctors.useQuery();

  if (doctor.isLoading) {
    return <Loader />;
  }

  if (doctor.error) {
    return <div>Error: {doctor.error.message}</div>;
  }

  return (
    <main>
      <Head>
        <title>Doctors - Dakthar.com</title>
        <meta name="description" content="Generated by create-t3-app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="mt-5 lg:mt-10">
        <DoctorTable doctors={doctor.data.doctors} />
      </section>
    </main>
  );
};

export default AdminDoctor;
