import Head from "next/head";
import { useAutoAnimate } from "@formkit/auto-animate/react";

// import { AppointmentTable } from "~/components/admin/AppointmentTable";
import { Loader } from "~/components/loader/Loader";
import { api } from "~/utils/api";

const AdminAppointments = () => {
  const appointments = api.appointment.getAllAppointments.useQuery();
  const [parent] = useAutoAnimate();

  if (appointments.isLoading) {
    return <Loader />;
  }

  if (appointments.isError) {
    return <div>Error: {appointments?.error?.message}</div>;
  }

  return (
    <>
      <Head>
        <title>Appointments - Dakthar.com</title>
        <meta name="description" content="Generated by create-t3-app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main ref={parent}>
        <section className="mt-5 lg:mt-10">
          {/* {appointments.data && (
            <AppointmentTable appointments={appointments.data.appointments} />
          )} */}
        </section>
      </main>
    </>
  );
};

export default AdminAppointments;
