import Head from "next/head";
import Link from "next/link";

const Index = () => {
  return (
    <>
      <Head>
        <title>Admin - Dakthar.com</title>
        <meta name="description" content="Generated by create-t3-app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="mx-[20px] mt-5 flex flex-col gap-3 lg:mx-[90px] lg:mt-10">
          <h2 className="mb-4 text-center text-[32px] font-[700] lg:text-[43px]">
            Available Options
          </h2>
          <Link
            href="/admin/appointment"
            className="btn rounded-[15px] bg-[#0099FF] px-[16px] py-[6px] text-[15px] font-bold leading-[30px] text-[#FFF] hover:bg-[#0099FF]"
            style={{ textTransform: "capitalize" }}
          >
            Get All Appointments
          </Link>
          <Link
            href="/admin/doctor"
            className="btn rounded-[15px] bg-[#0099FF] px-[16px] py-[6px] text-[15px] font-bold leading-[30px] text-[#FFF] hover:bg-[#0099FF]"
            style={{ textTransform: "capitalize" }}
          >
            Get All Doctors
          </Link>
        </div>
      </div>
    </>
  );
};

export default Index;
